In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv('/content/drive/MyDrive/Dataset/Dataset 1/Suicide_Detection.csv')
df1.head()

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [4]:
df2 = pd.read_csv('/content/drive/MyDrive/Dataset/Dataset 2/Depression_Suicide.csv')
df2.head()

,content,datetime,label
0,misstoriblack cool i have no tweet applic for...,2009-04-06 23:11:14,neutral
1,tiannachao i know just famili drama it lamehey...,2009-06-23 13:40:11,neutral
2,school email wont open and i have geographi st...,2009-06-01 10:26:07,neutral
3,piginthepok oh whi are you feel like that,2009-06-19 16:11:29,neutral
4,gahh noopeyton need to livethi is horribl,2009-05-11 22:01:32,neutral

In [5]:
# Drop the first column
df1 = df1.drop(df1.columns[0], axis=1)
df1.head()

                                                text        class
0  Ex Wife Threatening SuicideRecently I left my ...      suicide
1  Am I weird I don't get affected by compliments...  non-suicide
2  Finally 2020 is almost over... So I can never ...  non-suicide
3          i need helpjust help me im crying so hard      suicide
4  I’m so lostHello, my name is Adam (16) and I’v...      suicide

In [6]:
# Drop the first column
df2 = df2.drop(df2.columns[1], axis=1)
df2.head()

                                             content    label
0  misstoriblack cool  i have no tweet applic for...  neutral
1  tiannachao i know just famili drama it lamehey...  neutral
2  school email wont open and i have geographi st...  neutral
3          piginthepok oh whi are you feel like that  neutral
4          gahh noopeyton need to livethi is horribl  neutral

In [7]:
df1.isnull().sum()

text     0
class    0
dtype: int64

In [8]:
df2.isnull().sum()

content    0
label      0
dtype: int64

In [9]:
# Manually encode the labels
label_mapping = {'non-suicide': 0, 'suicide': 2}
df1['class'] = df1['class'].map(label_mapping)
df1.head()

                                                text  class
0  Ex Wife Threatening SuicideRecently I left my ...      2
1  Am I weird I don't get affected by compliments...      0
2  Finally 2020 is almost over... So I can never ...      0
3          i need helpjust help me im crying so hard      2
4  I’m so lostHello, my name is Adam (16) and I’v...      2

In [10]:
# Count occurrences of each label
df1['class'].value_counts()

class
2    116037
0    116037
Name: count, dtype: int64

In [11]:
# Manually encode the labels
label_mapping = {'neutral': 0, 'depression': 1, 'suicide': 2}
df2['Label'] = df2['label'].map(label_mapping)
df2.head()

                                             content    label  Label
0  misstoriblack cool  i have no tweet applic for...  neutral      0
1  tiannachao i know just famili drama it lamehey...  neutral      0
2  school email wont open and i have geographi st...  neutral      0
3          piginthepok oh whi are you feel like that  neutral      0
4          gahh noopeyton need to livethi is horribl  neutral      0

In [12]:
# Count occurrences of each label
df2['Label'].value_counts()

Label
1    391043
2    386934
0    290422
Name: count, dtype: int64

In [13]:
# Filter out rows where 'class' is 0 or 2
df2 = df2[~df2['Label'].isin([0, 2])]
df2.head()

                                                  content       label  Label
290422  most day i wonder whi do i do the thing i do w...  depression      1
290423  im so far gone iv been depress for about 6 yea...  depression      1
290424  sorri for the super long post but i need to ve...  depression      1
290425  today i am go to think differently not forever...  depression      1
290426  im in depression again this is the worst feel ...  depression      1

In [14]:
# Count occurrences of each label
df2['Label'].value_counts()

Label
1    391043
Name: count, dtype: int64

In [15]:
# Drop the first column
df2 = df2.drop(df2.columns[1], axis=1)
df2.head()

                                                  content  Label
290422  most day i wonder whi do i do the thing i do w...      1
290423  im so far gone iv been depress for about 6 yea...      1
290424  sorri for the super long post but i need to ve...      1
290425  today i am go to think differently not forever...      1
290426  im in depression again this is the worst feel ...      1

In [16]:
# Rename 'class' column to 'labels' in df1
df1 = df1.rename(columns={'class': 'Label'})
df2 = df2.rename(columns={'content': 'text'})

In [17]:
# Concatenate df1 and df2
merged_df = pd.concat([df1, df2], ignore_index=True)

# Shuffle the dataset
df = merged_df.sample(frac=1).reset_index(drop=True)
df.head()

                                                text  Label
0  so to start my girlfriend of 4 year told me sh...      1
1  iv been gradual get better iv accept my diagno...      1
2  i just had my first session with a psychologis...      1
3  im so letharg today im at work do absolut noth...      1
4  long stori short i start take xanax aback in j...      1

In [18]:
# Count occurrences of each label
df['Label'].value_counts()

Label
1    391043
2    116037
0    116037
Name: count, dtype: int64

In [19]:
df.to_csv('/content/drive/MyDrive/Dataset/Dataset 3/2_types_raw_data', index=False)

In [24]:
# Filter the dataset to get 1,00,000 samples for each label
label_0 = df[df['Label'] == 0].sample(n=100000, random_state=1)
label_1 = df[df['Label'] == 1].sample(n=100000, random_state=1)
label_2 = df[df['Label'] == 2].sample(n=100000, random_state=1)

# Concatenate these samples into a single dataframe
df_balanced = pd.concat([label_0, label_1, label_2])

# Shuffle the concatenated dataframe
df = df_balanced.sample(frac=1, random_state=1).reset_index(drop=True)
df.head(10)

                                                text  Label
0  I'm done with it all. Any tips?First of all, i...      2
1  i 20m was a problem child when grow up i frequ...      1
2  I officially hate my school We have to start p...      0
3  but onc again depress love to take that from m...      1
4  Starting today, I'm going to attempt to fix my...      0
5  i first start off hate peopleand then even mor...      1
6  Honestly I don’t know what to doI feel like my...      2
7  Whoever comments garlic bread on this post Has...      0
8  I just don't know what to doFor about 2 years ...      2
9  Could I get some help So my Spanish teach had ...      0

In [25]:
# Count occurrences of each label
df['Label'].value_counts()

Label
2    100000
1    100000
0    100000
Name: count, dtype: int64

In [26]:
df.to_csv('/content/drive/MyDrive/Dataset/Dataset 3/2_types_3lakh', index=False)

In [27]:
import pandas as pd
import nltk
from nltk.corpus import words
from nltk.tokenize import word_tokenize
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer, WordNetLemmatizer

In [28]:
# Download necessary NLTK data
nltk.download('words')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [29]:
# Initialize objects for stemming and lemmatization
stemmer = SnowballStemmer(language='english')
lemmatizer = WordNetLemmatizer()

In [30]:
# Load English words set
english_words = set(words.words())

In [31]:
# Function to filter non-English words for Labels 0 and 2
def filter_non_english_basic(text):
    return ' '.join([word for word in text.split() if word.lower() in english_words])

In [32]:
# Extend the list with common stemmed and lemmatized forms
extended_english_words = set()

for word in english_words:
    # Add the original word
    extended_english_words.add(word)
    # Add the stemmed version of the word
    extended_english_words.add(stemmer.stem(word))
    # Add the lemmatized version of the word
    extended_english_words.add(lemmatizer.lemmatize(word))

# Function to filter non-English words for Label 1
def filter_non_english_extended(text):
    return ' '.join([word for word in text.split() if word.lower() in extended_english_words])

In [33]:
# Function to apply the correct filter based on label
def conditional_filter(text, label):
    if label == 1:
        return filter_non_english_extended(text)
    else:
        return filter_non_english_basic(text)

In [35]:
# Apply the filter conditionally
df['filtered_text_eng'] = df.apply(lambda row: conditional_filter(row['text'], row['Label']), axis=1)

In [36]:
# Function for text preprocessing
def preprocess_text(text):

    # Remove URL
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', text)
    text = re.sub(r'#([^\s]+)', '', text)

    # Remove all the special characters
    text = re.sub(r'\W', ' ', text)

    # Remove all single characters
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text)

    # Remove single characters from the start
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', text)

    # Remove numeric
    text = re.sub(r'\d+', '', text)

    # Substituting multiple spaces with single space
    text = re.sub(r'\s+', ' ', text, flags=re.I)

    # Convert to Lowercase
    text = text.lower()

    # Remove whitespace at begin and end string
    text = text.strip()

    # Tokenize the text
    words = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Stemming
    words = [stemmer.stem(word) for word in words]

    # Lemmatization
    words = [lemmatizer.lemmatize(word) for word in words]

    # Join the words back into a string
    processed_text = ' '.join(words)

    return words, processed_text

In [37]:
# Apply preprocessing to the 'Text' column
df['tokenized_text'], df['Preprocessed_Text'] = zip(*df['filtered_text_eng'].apply(preprocess_text))
df.head(20)

,text,Label,filtered_text_eng,tokenized_text,Preprocessed_Text
0,"I'm done with it all. Any tips?First of all, i...",2,done with it Any of if going to comment get or...,"[done, go, comment, get, plea, understand, wan...",done go comment get plea understand want hear ...
1,i 20m was a problem child when grow up i frequ...,1,i was a problem child when grow up i frequent ...,"[problem, child, grow, frequent, got, troubl, ...",problem child grow frequent got troubl junior ...
2,I officially hate my school We have to start p...,0,I officially hate my school We have to start o...,"[offici, hate, school, start, enter, caus, fix]",offici hate school start enter caus fix
3,but onc again depress love to take that from m...,1,but onc again depress love to take that from m...,"[onc, depress, love, take, angri, want, cri, w...",onc depress love take angri want cri wont come...
4,"Starting today, I'm going to attempt to fix my...",0,Starting going to attempt to fix my sleep sche...,"[start, go, attempt, fix, sleep, schedul, scho...",start go attempt fix sleep schedul school coup...
5,i first start off hate peopleand then even mor...,1,i first start off hate then even more peopl an...,"[first, start, hate, even, peopl, came, conclu...",first start hate even peopl came conclus hate ...
6,Honestly I don’t know what to doI feel like my...,2,Honestly I know what to feel like my future wi...,"[honest, know, feel, like, futur, go, addict, ...",honest know feel like futur go addict alcohol ...
7,Whoever comments garlic bread on this post Has...,0,Whoever garlic bread on this post to eat whole...,"[whoever, garlic, bread, post, eat, whole, chees]",whoever garlic bread post eat whole chees
8,I just don't know what to doFor about 2 years ...,2,I just know what to about had I quit school at...,"[know, quit, school, travel, got, lot, short, ...",know quit school travel got lot short term bac...
9,Could I get some help So my Spanish teach had ...,0,Could I get some help So my teach had the glor...,"[could, get, help, teach, glorious, idea, proj...",could get help teach glorious idea project cre...
10,so i start cut again today it been anoth 3 wee...,1,so i start cut again today it been anoth week ...,"[start, cut, today, anoth, week, sign, work, f...",start cut today anoth week sign work find hard...
11,i take pills without water... 😈😈😈 i guess im j...,0,i take without i guess just built different,"[take, without, guess, built, differ]",take without guess built differ
12,i guess ive spent a larg portion from 16 year ...,1,i guess spent a larg portion from year year ol...,"[guess, spent, larg, portion, year, year, old,...",guess spent larg portion year year old onward ...
13,as far as i can rememb i was a geek it was mos...,1,as far as i can rememb i was a geek it was mos...,"[far, rememb, geek, outlet, fun, think, hardsh...",far rememb geek outlet fun think hardship life...
14,"horny teens of reddit, describe your process t...",0,horny teens of describe your process to findin...,"[horni, teen, describ, process, find, good, vi...",horni teen describ process find good video fil...
15,for mani year i have suffer from depress and a...,1,for mani year i have suffer from depress and a...,"[mani, year, suffer, depress, emot, feel, come...",mani year suffer depress emot feel come stori ...
16,I have made a life changing discovery Basicall...,0,I have made a life discovery Basically if you ...,"[made, life, discoveri, basic, guy, know, dick...",made life discoveri basic guy know dick piss e...
17,i have suffer and continu to suffer from depre...,1,i have suffer and continu to suffer from depre...,"[suffer, continu, suffer, depress, sever, diff...",suffer continu suffer depress sever differ sin...
18,WellBye,2,,[],
19,i dislike 99% of pplI f'ing hate EVERYONE. eve...,2,i dislike of hate everyone me I see in myself ...,"[dislik, hate, everyon, see, see, hate, submis...",dislik hate everyon see see hate submiss hate ...

In [38]:
df.isnull().sum()

text                 0
Label                0
filtered_text_eng    0
tokenized_text       0
Preprocessed_Text    0
dtype: int64

In [39]:
df.shape

(300000, 5)

In [40]:
df.to_csv('/content/drive/MyDrive/Dataset/Dataset 3/2_types_preprocessed_3lakh.csv', index=False, encoding='utf-8')

In [41]:
df.head(20)

,text,Label,filtered_text_eng,tokenized_text,Preprocessed_Text
0,"I'm done with it all. Any tips?First of all, i...",2,done with it Any of if going to comment get or...,"[done, go, comment, get, plea, understand, wan...",done go comment get plea understand want hear ...
1,i 20m was a problem child when grow up i frequ...,1,i was a problem child when grow up i frequent ...,"[problem, child, grow, frequent, got, troubl, ...",problem child grow frequent got troubl junior ...
2,I officially hate my school We have to start p...,0,I officially hate my school We have to start o...,"[offici, hate, school, start, enter, caus, fix]",offici hate school start enter caus fix
3,but onc again depress love to take that from m...,1,but onc again depress love to take that from m...,"[onc, depress, love, take, angri, want, cri, w...",onc depress love take angri want cri wont come...
4,"Starting today, I'm going to attempt to fix my...",0,Starting going to attempt to fix my sleep sche...,"[start, go, attempt, fix, sleep, schedul, scho...",start go attempt fix sleep schedul school coup...
5,i first start off hate peopleand then even mor...,1,i first start off hate then even more peopl an...,"[first, start, hate, even, peopl, came, conclu...",first start hate even peopl came conclus hate ...
6,Honestly I don’t know what to doI feel like my...,2,Honestly I know what to feel like my future wi...,"[honest, know, feel, like, futur, go, addict, ...",honest know feel like futur go addict alcohol ...
7,Whoever comments garlic bread on this post Has...,0,Whoever garlic bread on this post to eat whole...,"[whoever, garlic, bread, post, eat, whole, chees]",whoever garlic bread post eat whole chees
8,I just don't know what to doFor about 2 years ...,2,I just know what to about had I quit school at...,"[know, quit, school, travel, got, lot, short, ...",know quit school travel got lot short term bac...
9,Could I get some help So my Spanish teach had ...,0,Could I get some help So my teach had the glor...,"[could, get, help, teach, glorious, idea, proj...",could get help teach glorious idea project cre...
10,so i start cut again today it been anoth 3 wee...,1,so i start cut again today it been anoth week ...,"[start, cut, today, anoth, week, sign, work, f...",start cut today anoth week sign work find hard...
11,i take pills without water... 😈😈😈 i guess im j...,0,i take without i guess just built different,"[take, without, guess, built, differ]",take without guess built differ
12,i guess ive spent a larg portion from 16 year ...,1,i guess spent a larg portion from year year ol...,"[guess, spent, larg, portion, year, year, old,...",guess spent larg portion year year old onward ...
13,as far as i can rememb i was a geek it was mos...,1,as far as i can rememb i was a geek it was mos...,"[far, rememb, geek, outlet, fun, think, hardsh...",far rememb geek outlet fun think hardship life...
14,"horny teens of reddit, describe your process t...",0,horny teens of describe your process to findin...,"[horni, teen, describ, process, find, good, vi...",horni teen describ process find good video fil...
15,for mani year i have suffer from depress and a...,1,for mani year i have suffer from depress and a...,"[mani, year, suffer, depress, emot, feel, come...",mani year suffer depress emot feel come stori ...
16,I have made a life changing discovery Basicall...,0,I have made a life discovery Basically if you ...,"[made, life, discoveri, basic, guy, know, dick...",made life discoveri basic guy know dick piss e...
17,i have suffer and continu to suffer from depre...,1,i have suffer and continu to suffer from depre...,"[suffer, continu, suffer, depress, sever, diff...",suffer continu suffer depress sever differ sin...
18,WellBye,2,,[],
19,i dislike 99% of pplI f'ing hate EVERYONE. eve...,2,i dislike of hate everyone me I see in myself ...,"[dislik, hate, everyon, see, see, hate, submis...",dislik hate everyon see see hate submiss hate ...